services:
  # The Backend Service
  - type: web
    name: pack-yours-backend
    env: node
    plan: free
    root: backend  # Tells Render the code is in the 'backend' folder
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: MONGO_URI
        fromGroup: pack-yours-settings
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 10000

envVarGroups:
  - name: pack-yours-settings
    envVars:
      - key: MONGO_URI
        sync: false # You will need to enter this value in Render Dashboard
